# Generated by Django 5.2.1 on 2025-05-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('writing', 'Writing'), ('coding', 'Coding'), ('other', 'Other'), ('web', 'Web Development'), ('marketing', 'Marketing')], max_length=50),
        ),
    ]
