# Generated by Django 5.2.1 on 2025-05-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_featured',
        ),
    ]
