# Generated by Django 5.2.1 on 2025-05-24 09:41

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('urgent', 'Urgent'), ('featured', 'Featured'), ('remote', 'Remote'), ('onsite', 'On-site')], max_length=29),
        ),
    ]
