# Generated by Django 5.2.1 on 2025-05-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
    ]
