# Generated by Django 5.2.1 on 2025-05-26 09:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_profile_image_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', help_text='Select your experience level', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('new', 'New Seller'), ('verified', 'Verified Freelancer'), ('top', 'Top Rated Freelancer'), ('pro', 'Pro Seller')], default='new', editable=False, help_text='Seller level is assigned automatically', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('django', 'Django'), ('react', 'React'), ('flask', 'Flask'), ('node', 'Node.js'), ('bootstrap', 'Bootstrap')], max_length=33),
        ),
        migrations.AddField(
            model_name='service',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('html', 'HTML'), ('css', 'CSS')], max_length=31),
        ),
    ]
