# Generated by Django 5.2.1 on 2025-05-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
