# Generated by Django 5.2.1 on 2025-05-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
    ]
