# Generated by Django 5.2.1 on 2025-05-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_review_reviewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
