# Generated by Django 5.2.1 on 2025-05-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_profile_level_payment_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
